v0.2
* additional config option to also download the Linux AppImage
* if downloaded DMG or AppImage files already exists in the download location, sbdl will check the files' integrity first (7-zip dependency needed for AppImage files), and will only unlink corrupt downloads

diff --git a/sbdl b/sbdl
--- a/sbdl
+++ b/sbdl
@@ -1,7 +1,7 @@
 #!/bin/zsh
 # shellcheck shell=bash
 
-# sbdl 0.1
+# sbdl 0.2
 # download Superbacked & auxiliary files
 # shell script for LaunchAgent
 
@@ -15,6 +15,7 @@ accountname=$(id -un)
 bundleid="com.superbacked.std"
 appdlurl1="https://superbacked.com/api/downloads/superbacked-"
 appdlurl2="-latest.dmg?license="
+appdlurl3="-latest.AppImage?license="
 gitdlurl="https://raw.githubusercontent.com/superbacked/superbacked/main/releases/v"
 
 logloc="$HOME/Library/Logs/local.$accountname.$process.log"
@@ -24,7 +25,7 @@ exec > >(tee -a "$logloc") 2>&1
 configdir="$HOME/Library/Application Support/SuperbackedDownloader"
 ! [[ -d "$configdir" ]] && mkdir -p "$configdir" 2>/dev/null
 configloc="$configdir/sbdl.cfg"
-! [[ -f "$configloc" ]] && echo -e "# Mandatory: please enter your personal software license key\nLicense: <yourLicenseKey>\n# Optional: enter the full path to your preferred download folder\nDownloadPath: \n# Optional: release label can be set to 'op' (special operator release for law firms)\nReleaseLabel: " > "$configloc" 2>/dev/null
+! [[ -f "$configloc" ]] && echo -e "# Mandatory: please enter your personal software license key\nLicense: <yourLicenseKey>\n# Optional: enter the full path to your preferred download folder\nDownloadPath: \n# Optional: replace with '1', 'y', 'yes', 'Y', 'YES' or 'Yes' for additional Linux AppImage download\nLinuxDownload: no\n# Optional: release label can be set to 'op' (special operator release for law firms)\nReleaseLabel: " > "$configloc" 2>/dev/null
 
 # function: error beep
 _beep () {
@@ -98,7 +99,7 @@ if ! [[ $apploc ]] ; then
 	echo -e "NOTE: Superbacked not installed yet!\nRemote version: $version"
 else
 	echo "INFO: software installed at $apploc"
-	# read local version number
+	# read local version numbers
 	plistloc="$apploc/Contents/Info.plist"
 	localversion=$(defaults read "$plistloc" CFBundleVersion 2>/dev/null)
 	if ! [[ $localversion ]] ; then
@@ -132,6 +133,17 @@ else
 	echo "INFO: using target folder $dlpath"
 fi
 
+# check configuration for Linux download
+linuxinfo=$(echo "$config" | grep "^LinuxDownload:" | awk -F":" '{print $2}' | xargs | sed -e 's/^ *//' -e 's/ *$//')
+if [[ $linuxinfo =~ ^(1|y|Y|yes|YES|Yes)$ ]] ; then
+	linuxdl=true
+	echo "INFO: Linux AppImage download enabled"
+	finalappdlurl_linux="$appdlurl1$label$appdlurl3$license"
+else
+	linuxdl=false
+	echo "INFO: Linux AppImage download disabled"
+fi
+
 # download auxiliary files from GitHub first
 sleep 1
 echo "Downloading auxiliary files from GitHub..."
@@ -159,21 +171,83 @@ else
 	_notify "☑️ Download finished" "SHA256SUMS.asc"
 fi
 
-# download main application
+# download main application DMG
 filename=$(curl -I "$finalappdlurl" 2>&1 | grep "filename=" | awk -F"filename=" '{print $2}' | xargs | tr -cd '\40-\176')
 ! [[ $filename ]] && filename="superbacked-$label-$version.dmg"
 echo "Downloading: $filename"
-_notify "⏳ Please wait: downloading…" "$filename" &
-rm -f ./"$filename" 2>/dev/null
-if ! curl -sL --connect-timeout 10 -o ./"$filename" "$finalappdlurl" 2>/dev/null ; then
-	echo "ERROR: download failed!"
-	_notify "❌ Error: download!" "$filename"
-	_beep
-	exit 1
+if [[ -f ./"$filename" ]] ; then
+	echo "NOTE: file already exists - checking..."
+	if hdiutil verify ./"$filename" &>/dev/null ; then
+		echo "INFO: file already downloaded"
+		_notify "ℹ️ File already exists" "$filename"
+		_info
+		dmgdl=false
+	else
+		echo "INFO: DMG file corrupted - will unlink..."
+		dmgdl=true
+	fi
 else
-	echo "SUCCESS: downloaded Superbacked v$version"
-	_notify "✅ Download finished" "Superbacked v$version"
-	_success
+	dmgdl=true
+	sleep 1
+fi
+if $dmgdl ; then
+	_notify "⏳ Please wait: downloading…" "$filename" &
+	echo "Downloading: $filename"
+	rm -f ./"$filename" 2>/dev/null
+	if ! curl -sL --connect-timeout 10 -o ./"$filename" "$finalappdlurl" 2>/dev/null ; then
+		echo "ERROR: download failed!"
+		_notify "❌ Error: download!" "$filename"
+		_beep
+		errors=true
+	else
+		echo "SUCCESS: downloaded Superbacked v$version (macOS DMG)"
+		_notify "✅ Download finished" "Superbacked v$version (macOS)"
+		_success
+	fi
+fi
+
+# download main application (AppImage/Linux)
+if $linuxdl ; then
+	filename_linux=$(curl -I "$finalappdlurl_linux" 2>&1 | grep "filename=" | awk -F"filename=" '{print $2}' | xargs | tr -cd '\40-\176')
+	! [[ $filename_linux ]] && filename_linux="superbacked-$label-$version.AppImage"
+	echo "Downloading: $filename_linux"
+	if [[ -f ./"$filename_linux" ]] ; then
+		echo "NOTE: file already exists - checking..."
+		if ! command -v 7z &>/dev/null ; then
+			echo "INFO: file already downloaded"
+			_notify "ℹ️ File already exists" "$filename_linux"
+			_info
+			aidl=false
+		else
+			if 7z t ./"$filename_linux" 2>&1 | grep "^Can not open the file as archive$" &>/dev/null ; then
+				echo "INFO: AppImage file corrupted - will unlink..."
+				aidl=true
+			else
+				echo "INFO: file already downloaded"
+				_notify "ℹ️ File already exists" "$filename_linux"
+				_info
+				aidl=false
+			fi
+		fi
+	else
+		aidl=true
+		sleep 1
+	fi
+	if $aidl ; then
+		echo "Downloading: $filename_linux"
+		_notify "⏳ Please wait: downloading…" "$filename_linux" &
+		rm -f ./"$filename_linux" 2>/dev/null
+		if ! curl -sL --connect-timeout 10 -o ./"$filename_linux" "$finalappdlurl_linux" 2>/dev/null ; then
+			echo "ERROR: download failed!"
+			_notify "❌ Error: download!" "$filename_linux"
+			_beep
+			errors=true
+		else
+			echo "SUCCESS: downloaded Superbacked v$version (Linux AppImage)"
+			_notify "✅ Download finished" "Superbacked v$version (Linux)"
+			_success
+		fi
+	fi
 fi
 
 if $errors ; then
